# Generated by Django 5.0.2 on 2024-03-06 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firebase_config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firebasefaceencodings',
            old_name='user_email',
            new_name='user_uid',
        ),
    ]
