# Generated by Django 5.0.2 on 2024-03-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase_config', '0002_rename_user_email_firebasefaceencodings_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebasefaceencodings',
            name='title',
            field=models.CharField(default='dummy@gmail.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='firebasefaceencodings',
            name='user_uid',
            field=models.CharField(max_length=200),
        ),
    ]
