# Generated by Django 5.0.2 on 2024-03-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase_config', '0003_alter_firebasefaceencodings_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebasefaceencodings',
            name='face_encodings',
            field=models.JSONField(),
        ),
    ]
