# Generated by Django 5.0.2 on 2024-03-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_field',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
