# Generated by Django 5.0.2 on 2024-03-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_title_post_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_email',
            field=models.CharField(default='dummy@gmail.com', max_length=200),
        ),
    ]
